# Use version 3.8 of the Docker Compose file format
version: '3.8'

# Define the services to be run with Docker Compose
services:
  # Create a service named "wg" (short for WireGuard)
  wg:
    # Define the build configuration for the "wg" service
    build:
      # Set the build context to the current directory
      context: .
      # Specify the Dockerfile to use for building the image
      dockerfile: Dockerfile

    # Set the container name to "wg"
    container_name: wg
    # Restart the container automatically unless it was manually stopped
    restart: unless-stopped
    # Grant the container privileged access to the host system
    privileged: true
    # Set the DNS server for the container to use
    dns:
      - 192.168.1.1

    # Map devices from the host to the container
    devices:
      - /dev/net/tun

    # Add Linux capabilities to the container
    cap_add:
      - NET_ADMIN # Perform network administration tasks
      - SYS_MODULE # Load and unload kernel modules
      - SYS_ADMIN # Perform a wide range of system administration tasks
      - NET_RAW # Use RAW and PACKET sockets
      - NET_BIND_SERVICE # Bind a socket to privileged ports (<1024)

    # Expose and map ports from the container to the host
    ports:
      - "7777:3128" # Map host port 7777 to container port 3128 (HTTP proxy)
      - "8888:1080" # Map host port 8888 to container port 1080 (SOCKS proxy)

    # Define environment variables for the container
    environment:
      PROXY_USER: example_user # Proxy username
      PROXY_PASS: example_password # Proxy password
      WIREGUARD_INTERFACE_PRIVATE_KEY: "examplePrivateKey" # WireGuard private key
      WIREGUARD_INTERFACE_DNS: "1.1.1.1, 8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, 2001:4860:4860::8844" # WireGuard DNS servers
      WIREGUARD_INTERFACE_ADDRESS: "172.16.0.2/32" # WireGuard interface IP address not ipv6 range supported
      WIREGUARD_PEER_PUBLIC_KEY: "examplePublicKey" # WireGuard peer public key
      WIREGUARD_PEER_ALLOWED_IPS: "0.0.0.0/0" # WireGuard allowed IPs for the peer
      WIREGUARD_PEER_ENDPOINT: "example.server.ip:2048" # WireGuard peer endpoint
